### ISSUE TITLE
Brute Force encryption tool issue

### ISSUE THREAD

**Issue by kswartz** [santoku/Santoku-Linux#10] opened 2012-08-16 21:12 UTC
When running ./bruteforce_stdcrypto.py in /opt/santoku/forensics/vAndBrute, receive a : No such file or directory error, though the file is present in the folder.

**Comment by thomascannon** [comment] 2012-08-16 21:13
Duplicate of issue #4 which will fix the problem.

**Closed as completed by thomascannon** 2012-08-16 21:13 UTC
Labels: bug, duplicate
